;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
in 1
; row 0 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b18 1
knit + b17 1
; row 1 X+
xfer b18 fs18
rack -1
xfer fs18 b19
rack 0
; row 2 L
knit - b17 1
knit - b18 1
knit - b19 1
; row 3 X
xfer b19 fs19
xfer b18 fs18
xfer b17 fs17
rack 1
xfer fs19 b18
xfer fs18 b17
xfer fs17 b16
rack 0
; row 4 R
knit + b18 1
knit + b17 1
knit + b16 1
knit + b15 1
knit + b14 1
; row 5 L
knit - b14 1
knit - b15 1
; row 6 R
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 7 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
; row 8 X
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack -1
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
rack 0
; row 9 Flip
xfer b18 f18
; row 10 X
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs17 b18
xfer fs16 b17
xfer fs15 b16
xfer fs14 b15
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 11 R
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
; row 12 L
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit - b1 1
knit - b2 1
knit - b3 1
knit - b4 1
; row 13 X+
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack 1
xfer bs2 f3
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
xfer bs13 f14
xfer bs14 f15
xfer bs15 f16
xfer bs16 f17
xfer bs17 f18
xfer bs18 f19
rack 0
; row 14 R
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
; row 15 Flip
xfer f19 b19
; row 16 X
xfer b19 fs19
xfer b18 fs18
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs19 b18
xfer fs18 b17
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 17 L
knit - b18 1
knit - f18 1
knit - f17 1
knit - f16 1
; row 18 R
knit + f16 1
knit + f17 1
knit + f18 1
knit + b18 1
; row 19 L
knit - b18 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
; row 20 R
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b18 1
knit + b17 1
knit + b16 1
; row 21 X
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs16 b17
xfer fs15 b16
xfer fs14 b15
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 22 R
knit + b16 1
; row 23 L
knit - b16 1
knit - b17 1
; row 24 R
knit + b17 1
knit + b16 1
; row 25 L
knit - b16 1
knit - b17 1
knit - b18 1
knit - f18 1
; row 26 R
knit + f18 1
knit + b18 1
knit + b17 1
knit + b16 1
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
; row 27 L
knit - b12 1
knit - b13 1
knit - b14 1
knit - b15 1
; row 28 R
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
; row 29 L
knit - b7 1
knit - b8 1
knit - b9 1
knit - b10 1
knit - b11 1
knit - b12 1
knit - b13 1
knit - b14 1
knit - b15 1
; row 30 R
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
; row 31 L
knit - b5 1
knit - b6 1
; row 32 R
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
; row 33 R
knit + f0 1
knit + f1 1
; row 34 L
knit - f1 1
knit - f0 1
; row 35 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
; row 36 L
knit - f18 1
knit - f17 1
; row 37 R
knit + f17 1
knit + f18 1
knit + b18 1
knit + b17 1
knit + b16 1
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
; row 38 L
knit - b6 1
knit - b7 1
knit - b8 1
knit - b9 1
knit - b10 1
knit - b11 1
knit - b12 1
knit - b13 1
knit - b14 1
knit - b15 1
knit - b16 1
knit - b17 1
; row 39 R
knit + b17 1
knit + b16 1
knit + b15 1
; row 40 X+
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
rack -1
xfer bs0 f-1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
rack 0
; row 41 L
knit - b15 1
knit - b16 1
knit - b17 1
knit - b18 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
; row 42 X
xfer f-1 bs-1
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack 1
xfer bs-1 f0
xfer bs0 f1
xfer bs1 f2
xfer bs2 f3
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
xfer bs13 f14
xfer bs14 f15
xfer bs15 f16
xfer bs16 f17
xfer bs17 f18
xfer bs18 f19
rack 0
; row 43 Flip
xfer f19 b19
; row 44 X
xfer b19 fs19
xfer b18 fs18
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs19 b18
xfer fs18 b17
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 45 R
knit + f5 1
knit + f6 1
knit + f7 1
; row 46 L
knit - f7 1
knit - f6 1
; row 47 R
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
; row 48 X
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
xfer f17 bs17
xfer f18 bs18
rack -1
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
xfer bs17 f16
xfer bs18 f17
rack 0
; row 49 Flip
xfer b18 f18
; row 50 X
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs17 b18
xfer fs16 b17
xfer fs15 b16
xfer fs14 b15
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 51 R
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b18 1
knit + b17 1
knit + b16 1
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
; row 52 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 53 X
xfer b18 fs18
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs18 b17
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 54 Flip
xfer f18 b18
; row 55 X
xfer b18 fs18
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs18 b17
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 56 R
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
; row 57 X
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 58 R
knit + b6 1
knit + b5 1
knit + b4 1
; row 59 X
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 60 X
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 61 Flip
xfer f17 b17
; row 62 X
xfer b17 fs17
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs17 b16
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 63 R
knit + b2 1
; row 64 L
knit - b2 1
knit - b3 1
; row 65 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 66 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
; row 67 L
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit - b0 1
knit - b1 1
knit - b2 1
; row 68 R
knit + b2 1
knit + b1 1
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
; row 69 X
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
rack -1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
rack 0
; row 70 Flip
xfer b16 f16
; row 71 X
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs15 b16
xfer fs14 b15
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 72 R
knit + f3 1
knit + f4 1
knit + f5 1
; row 73 L
knit - f5 1
knit - f4 1
knit - f3 1
; row 74 R
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
; row 75 X
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
xfer f16 bs16
rack -1
xfer bs13 f12
xfer bs14 f13
xfer bs15 f14
xfer bs16 f15
rack 0
; row 76 X
xfer b16 fs16
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs16 b15
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 77 L
knit - f12 1
knit - f11 1
; row 78 R
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + b15 1
knit + b14 1
knit + b13 1
knit + b12 1
knit + b11 1
knit + b10 1
; row 79 L
knit - b10 1
knit - b11 1
; row 80 R
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
; row 81 L
knit - b5 1
knit - b6 1
knit - b7 1
; row 82 X
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
rack 1
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
rack 0
; row 83 X
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs14 b15
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 84 L
knit - b8 1
knit - b9 1
knit - b10 1
; row 85 X
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
rack 1
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
rack 0
; row 86 Flip
xfer f15 b15
; row 87 X
xfer b15 fs15
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs15 b14
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 88 L
knit - b9 1
knit - b10 1
knit - b11 1
knit - b12 1
knit - b13 1
knit - b14 1
knit - f14 1
; row 89 R
knit + f14 1
knit + b14 1
; row 90 L
knit - b14 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
; row 91 X
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
rack 1
xfer bs0 f1
xfer bs1 f2
xfer bs2 f3
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
rack 0
; row 92 X
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
rack -1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
xfer bs13 f12
xfer bs14 f13
rack 0
; row 93 Flip
xfer b14 f14
; row 94 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 95 L
knit - f8 1
knit - f7 1
knit - f6 1
; row 96 X+
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
rack 1
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
xfer bs13 f14
xfer bs14 f15
rack 0
; row 97 X+
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
xfer f14 bs14
xfer f15 bs15
rack 1
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
xfer bs13 f14
xfer bs14 f15
xfer bs15 f16
rack 0
; row 98 R
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
; row 99 Flip
xfer f16 b16
; row 100 X
xfer b16 fs16
rack 1
xfer fs16 b15
rack 0
; row 101 L
knit - f9 1
knit - f8 1
knit - f7 1
; row 102 R
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + b15 1
; row 103 X
xfer f15 bs15
rack -1
xfer bs15 f14
rack 0
; row 104 Flip
xfer b15 f15
; row 105 X
xfer f15 bs15
rack -1
xfer bs15 f14
rack 0
; row 106 R
knit + b14 1
knit + b13 1
knit + b12 1
; row 107 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 108 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack -1
xfer fs13 b14
xfer fs12 b13
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
rack 0
; row 109 X
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
rack 1
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
rack 0
; row 110 Flip
xfer f14 b14
; row 111 X
xfer b14 fs14
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs14 b13
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 112 R
knit + b11 1
; row 113 L
knit - b11 1
knit - b12 1
; row 114 R
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
; row 115 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 116 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 117 Flip
xfer f13 b13
; row 118 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 119 R
knit + b7 1
knit + b6 1
knit + b5 1
; row 120 X
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 121 R
knit + b5 1
knit + b4 1
; row 122 X
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 123 X
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 124 Flip
xfer f12 b12
; row 125 X
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 126 R
knit + b2 1
knit + b1 1
; row 127 X
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs1 b2
xfer fs0 b1
rack 0
; row 128 R
knit + b1 1
; row 129 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
; row 130 L
knit - f3 1
knit - f2 1
; row 131 R
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
; row 132 L
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
; row 133 R
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
; row 134 X
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
; row 135 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 136 R
knit + f9 1
knit + f10 1
knit + b10 1
; row 137 L
knit - b10 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
; row 138 X
xfer f0 bs0
xfer f1 bs1
rack 1
xfer bs0 f1
xfer bs1 f2
rack 0
; row 139 X
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
rack -1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
rack 0
; row 140 Flip
xfer b10 f10
; row 141 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 142 L
knit - f0 1
knit - b1 1
knit - b2 1
; row 143 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 144 Flip
xfer f10 b10
; row 145 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 146 L
knit - b1 1
; row 147 R
knit + b1 1
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
; row 148 L
knit - f6 1
knit - f5 1
; row 149 R
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
; row 150 X
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 151 R
knit + b5 1
; row 152 L
knit - b5 1
knit - b6 1
; row 153 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
rack 1
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
rack 0
; row 154 Flip
xfer f9 b9
; row 155 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 156 L
knit - b5 1
; row 157 R
knit + b5 1
knit + b4 1
knit + b3 1
; row 158 L
knit - b3 1
knit - b4 1
; row 159 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
rack 1
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
rack 0
; row 160 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 161 L
knit - b5 1
knit - b6 1
knit - b7 1
knit - b8 1
knit - f8 1
; row 162 Flip
xfer f8 b8
; row 163 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 164 L
knit - f7 1
; row 165 R
knit + f7 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
; row 166 X
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs1 b2
xfer fs0 b1
rack 0
; row 167 R
knit + b1 1
out 1
