;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
in 1
; row 0 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 1 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 2 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 3 R
knit + f0 1
knit + f1 1
knit + f2 1
; row 4 X
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
; row 5 Flip
xfer b11 f11
; row 6 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 7 R
knit + f2 1
; row 8 L
knit - f2 1
knit - f1 1
knit - f0 1
knit - b1 1
knit - b2 1
; row 9 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 10 Flip
xfer f11 b11
; row 11 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 12 L
knit - b1 1
knit - b2 1
knit - b3 1
; row 13 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
; row 14 X
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
rack -1
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
rack 0
; row 15 Flip
xfer b10 f10
; row 16 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 17 R
knit + f5 1
; row 18 L
knit - f5 1
knit - f4 1
knit - f3 1
; row 19 R
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
; row 20 L
knit - f7 1
knit - f6 1
; row 21 R
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
; row 22 X
xfer f10 bs10
rack -1
xfer bs10 f9
rack 0
; row 23 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 24 R
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
; row 25 L
knit - b5 1
knit - b6 1
knit - b7 1
; row 26 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
rack 1
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
rack 0
; row 27 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 28 L
knit - b8 1
knit - b9 1
; row 29 X
xfer b9 fs9
rack 1
xfer fs9 b8
rack 0
; row 30 Flip
xfer f9 b9
; row 31 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 32 L
knit - b8 1
knit - f8 1
; row 33 R
knit + f8 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
; row 34 X
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 35 R
knit + b3 1
knit + b2 1
knit + b1 1
; row 36 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
; row 37 X
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack -1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
rack 0
; row 38 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 39 R
knit + f3 1
knit + f4 1
knit + f5 1
; row 40 X
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
rack -1
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
rack 0
; row 41 Flip
xfer b7 f7
; row 42 X
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 43 R
knit + f5 1
knit + f6 1
; row 44 X
xfer f6 bs6
xfer f7 bs7
rack -1
xfer bs6 f5
xfer bs7 f6
rack 0
; row 45 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 46 R
knit + f6 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
; row 47 X
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 48 R
knit + b3 1
knit + b2 1
knit + b1 1
; row 49 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
; row 50 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
; row 51 X+
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack 1
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
xfer fs0 b-1
rack 0
; row 52 X+
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
xfer b-1 fs-1
rack 1
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
xfer fs0 b-1
xfer fs-1 b-2
rack 0
; row 53 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
split + f6 bs6 1
rack 1
xfer bs6 f7
rack 0
knit + b6 1
split + b5 fs5 1
rack 1
xfer fs5 b4
rack 0
split + b3 fs3 1
rack 1
xfer fs3 b2
rack 0
knit + b1 1
knit + b0 1
split + b-1 fs-1 1
rack 1
xfer fs-1 b-2
rack 0
; row 54 X
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
xfer b-1 fs-1
xfer b-2 fs-2
rack -1
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
xfer fs-1 b0
xfer fs-2 b-1
rack 0
; row 55 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
xfer b-1 fs-1
rack -1
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
xfer fs-1 b0
rack 0
; row 56 Flip
xfer b8 f8
; row 57 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 58 X+
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 59 X+
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
rack 1
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
rack 0
; row 60 X+
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
rack 1
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
rack 0
; row 61 X+
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack 1
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
rack 0
; row 62 X+
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
rack 1
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
rack 0
; row 63 X+
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
xfer f13 bs13
rack 1
xfer bs2 f3
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
xfer bs12 f13
xfer bs13 f14
rack 0
; row 64 R
knit + f0 1
split + f1 bs1 1
rack 1
xfer bs1 f2
rack 0
split + f3 bs3 1
rack 1
xfer bs3 f4
rack 0
split + f5 bs5 1
rack 1
xfer bs5 f6
rack 0
split + f7 bs7 1
rack 1
xfer bs7 f8
rack 0
split + f9 bs9 1
rack 1
xfer bs9 f10
rack 0
knit + f11 1
knit + f12 1
split + f13 bs13 1
rack 1
xfer bs13 f14
rack 0
knit + b8 1
knit + b7 1
split + b6 fs6 1
rack 1
xfer fs6 b5
rack 0
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 65 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 66 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 67 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack -1
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
rack 0
; row 68 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
rack -1
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
rack 0
; row 69 Flip
xfer f14 b14
; row 70 X
xfer b14 fs14
rack 1
xfer fs14 b13
rack 0
; row 71 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
rack 1
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
rack 0
; row 72 Flip
xfer f13 b13
; row 73 X
xfer b13 fs13
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
rack 1
xfer fs13 b12
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
rack 0
; row 74 X
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 75 Flip
xfer f12 b12
; row 76 X
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 77 R
knit + f0 1
knit + f1 1
; row 78 L
knit - f1 1
knit - f0 1
knit - b0 1
; row 79 X+
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack 1
xfer bs8 f9
xfer bs9 f10
xfer bs10 f11
xfer bs11 f12
rack 0
; row 80 R
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
split + f7 bs7 1
rack 1
xfer bs7 f8
rack 0
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
; row 81 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs11 b12
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 82 L
knit - f12 1
knit - f11 1
; row 83 R
knit + f11 1
knit + f12 1
knit + b12 1
knit + b11 1
knit + b10 1
knit + b9 1
; row 84 L
knit - b9 1
knit - b10 1
; row 85 R
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
; row 86 L
knit - b7 1
knit - b8 1
; row 87 R
knit + b8 1
knit + b7 1
knit + b6 1
; row 88 L
knit - b6 1
knit - b7 1
knit - b8 1
knit - b9 1
knit - b10 1
knit - b11 1
knit - b12 1
; row 89 R
knit + b12 1
knit + b11 1
; row 90 L
knit - b11 1
knit - b12 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
; row 91 X
xfer f0 bs0
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack 1
xfer bs0 f1
xfer bs1 f2
xfer bs2 f3
xfer bs3 f4
xfer bs4 f5
xfer bs5 f6
xfer bs6 f7
xfer bs7 f8
xfer bs8 f9
rack 0
; row 92 X
xfer f1 bs1
xfer f2 bs2
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
xfer f12 bs12
rack -1
xfer bs1 f0
xfer bs2 f1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
xfer bs12 f11
rack 0
; row 93 X
xfer b12 fs12
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs12 b11
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 94 L
knit - f7 1
knit - f6 1
; row 95 R
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
; row 96 L
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
; row 97 R
knit + f2 1
knit + f3 1
; row 98 L
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit - b0 1
; row 99 R
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
; row 100 L
knit - f5 1
knit - f4 1
; row 101 R
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
; row 102 X
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
; row 103 Flip
xfer b11 f11
; row 104 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs10 b11
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 105 R
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
; row 106 L
knit - b2 1
knit - b3 1
knit - b4 1
knit - b5 1
; row 107 R
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
; row 108 L
knit - b2 1
knit - b3 1
knit - b4 1
knit - b5 1
; row 109 R
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
out 1
