;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
in 1
; row 0 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 1 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b11 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 2 X
xfer b0 fs0
rack -1
xfer fs0 b1
rack 0
; row 3 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
; row 4 X
xfer f3 bs3
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
xfer f10 bs10
xfer f11 bs11
rack -1
xfer bs3 f2
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
xfer bs10 f9
xfer bs11 f10
rack 0
; row 5 X
xfer b11 fs11
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs11 b10
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 6 R
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
knit + b4 1
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 7 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + b10 1
; row 8 Flip
xfer b10 f10
; row 9 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs9 b10
xfer fs8 b9
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 10 R
knit + b10 1
knit + b9 1
knit + b8 1
knit + b7 1
knit + b6 1
knit + b5 1
; row 11 X
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 12 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 13 Flip
xfer f10 b10
; row 14 X
xfer b10 fs10
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs10 b9
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 15 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
; row 16 X
xfer b0 fs0
rack -1
xfer fs0 b1
rack 0
; row 17 R
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
; row 18 X
xfer f4 bs4
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
xfer f9 bs9
rack -1
xfer bs4 f3
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
xfer bs9 f8
rack 0
; row 19 X
xfer b9 fs9
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs9 b8
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 20 R
knit + f4 1
knit + f5 1
; row 21 X
xfer f5 bs5
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack -1
xfer bs5 f4
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
rack 0
; row 22 Flip
xfer b8 f8
; row 23 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs7 b8
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 24 R
knit + f5 1
knit + f6 1
; row 25 X
xfer f6 bs6
xfer f7 bs7
xfer f8 bs8
rack -1
xfer bs6 f5
xfer bs7 f6
xfer bs8 f7
rack 0
; row 26 X
xfer b8 fs8
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs8 b7
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 27 R
knit + f6 1
knit + f7 1
knit + b7 1
knit + b6 1
; row 28 X
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
xfer b0 fs0
rack -1
xfer fs6 b7
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
xfer fs0 b1
rack 0
; row 29 R
knit + b6 1
knit + b5 1
; row 30 X
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack -1
xfer fs5 b6
xfer fs4 b5
xfer fs3 b4
xfer fs2 b3
xfer fs1 b2
rack 0
; row 31 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
rack 1
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
rack 0
; row 32 Flip
xfer f7 b7
; row 33 X
xfer b7 fs7
xfer b6 fs6
xfer b5 fs5
xfer b4 fs4
xfer b3 fs3
xfer b2 fs2
xfer b1 fs1
rack 1
xfer fs7 b6
xfer fs6 b5
xfer fs5 b4
xfer fs4 b3
xfer fs3 b2
xfer fs2 b1
xfer fs1 b0
rack 0
; row 34 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + b6 1
knit + b5 1
knit + b4 1
; row 35 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + b6 1
knit + b5 1
knit + b4 1
; row 36 R
knit + b3 1
knit + b2 1
knit + b1 1
knit + b0 1
out 1
